using System.Collections.Generic;


namespace UniGLTF.ShaderPropExporter
{
    public static partial class PreShaderPropExporter
    {
        [PreExportShader]
        static KeyValuePair<string, ShaderProps> Universal_Render_Pipeline_Toon 
        {
            get 
            {
                return new KeyValuePair<string, ShaderProps>(
                    "Universal Render Pipeline/Toon",
                    new ShaderProps
                    {
                        Properties = new ShaderProperty[]{
new ShaderProperty("_simpleUI", ShaderPropertyType.Float)
,new ShaderProperty("_utsVersionX", ShaderPropertyType.Float)
,new ShaderProperty("_utsVersionY", ShaderPropertyType.Float)
,new ShaderProperty("_utsVersionZ", ShaderPropertyType.Float)
,new ShaderProperty("_utsTechnique", ShaderPropertyType.Float)
,new ShaderProperty("_AutoRenderQueue", ShaderPropertyType.Float)
,new ShaderProperty("_StencilMode", ShaderPropertyType.Float)
,new ShaderProperty("_StencilComp", ShaderPropertyType.Float)
,new ShaderProperty("_StencilNo", ShaderPropertyType.Float)
,new ShaderProperty("_StencilOpPass", ShaderPropertyType.Float)
,new ShaderProperty("_StencilOpFail", ShaderPropertyType.Float)
,new ShaderProperty("_TransparentEnabled", ShaderPropertyType.Float)
,new ShaderProperty("_Metallic", ShaderPropertyType.Range)
,new ShaderProperty("_Smoothness", ShaderPropertyType.Range)
,new ShaderProperty("_SpecColor", ShaderPropertyType.Color)
,new ShaderProperty("_ClippingMode", ShaderPropertyType.Float)
,new ShaderProperty("_CullMode", ShaderPropertyType.Float)
,new ShaderProperty("_ZWriteMode", ShaderPropertyType.Float)
,new ShaderProperty("_ZOverDrawMode", ShaderPropertyType.Float)
,new ShaderProperty("_SPRDefaultUnlitColorMask", ShaderPropertyType.Float)
,new ShaderProperty("_SRPDefaultUnlitColMode", ShaderPropertyType.Float)
,new ShaderProperty("_ClippingMask", ShaderPropertyType.TexEnv)
,new ShaderProperty("_IsBaseMapAlphaAsClippingMask", ShaderPropertyType.Float)
,new ShaderProperty("_Inverse_Clipping", ShaderPropertyType.Float)
,new ShaderProperty("_Clipping_Level", ShaderPropertyType.Range)
,new ShaderProperty("_Tweak_transparency", ShaderPropertyType.Range)
,new ShaderProperty("_MainTex", ShaderPropertyType.TexEnv)
,new ShaderProperty("_BaseMap", ShaderPropertyType.TexEnv)
,new ShaderProperty("_BaseColor", ShaderPropertyType.Color)
,new ShaderProperty("_Color", ShaderPropertyType.Color)
,new ShaderProperty("_Is_LightColor_Base", ShaderPropertyType.Float)
,new ShaderProperty("_1st_ShadeMap", ShaderPropertyType.TexEnv)
,new ShaderProperty("_Use_BaseAs1st", ShaderPropertyType.Float)
,new ShaderProperty("_1st_ShadeColor", ShaderPropertyType.Color)
,new ShaderProperty("_Is_LightColor_1st_Shade", ShaderPropertyType.Float)
,new ShaderProperty("_2nd_ShadeMap", ShaderPropertyType.TexEnv)
,new ShaderProperty("_Use_1stAs2nd", ShaderPropertyType.Float)
,new ShaderProperty("_2nd_ShadeColor", ShaderPropertyType.Color)
,new ShaderProperty("_Is_LightColor_2nd_Shade", ShaderPropertyType.Float)
,new ShaderProperty("_NormalMap", ShaderPropertyType.TexEnv)
,new ShaderProperty("_BumpScale", ShaderPropertyType.Range)
,new ShaderProperty("_Is_NormalMapToBase", ShaderPropertyType.Float)
,new ShaderProperty("_Set_SystemShadowsToBase", ShaderPropertyType.Float)
,new ShaderProperty("_Tweak_SystemShadowsLevel", ShaderPropertyType.Range)
,new ShaderProperty("_BaseColor_Step", ShaderPropertyType.Range)
,new ShaderProperty("_BaseShade_Feather", ShaderPropertyType.Range)
,new ShaderProperty("_ShadeColor_Step", ShaderPropertyType.Range)
,new ShaderProperty("_1st2nd_Shades_Feather", ShaderPropertyType.Range)
,new ShaderProperty("_1st_ShadeColor_Step", ShaderPropertyType.Range)
,new ShaderProperty("_1st_ShadeColor_Feather", ShaderPropertyType.Range)
,new ShaderProperty("_2nd_ShadeColor_Step", ShaderPropertyType.Range)
,new ShaderProperty("_2nd_ShadeColor_Feather", ShaderPropertyType.Range)
,new ShaderProperty("_StepOffset", ShaderPropertyType.Range)
,new ShaderProperty("_Is_Filter_HiCutPointLightColor", ShaderPropertyType.Float)
,new ShaderProperty("_Set_1st_ShadePosition", ShaderPropertyType.TexEnv)
,new ShaderProperty("_Set_2nd_ShadePosition", ShaderPropertyType.TexEnv)
,new ShaderProperty("_ShadingGradeMap", ShaderPropertyType.TexEnv)
,new ShaderProperty("_Tweak_ShadingGradeMapLevel", ShaderPropertyType.Range)
,new ShaderProperty("_BlurLevelSGM", ShaderPropertyType.Range)
,new ShaderProperty("_HighColor", ShaderPropertyType.Color)
,new ShaderProperty("_HighColor_Tex", ShaderPropertyType.TexEnv)
,new ShaderProperty("_Is_LightColor_HighColor", ShaderPropertyType.Float)
,new ShaderProperty("_Is_NormalMapToHighColor", ShaderPropertyType.Float)
,new ShaderProperty("_HighColor_Power", ShaderPropertyType.Range)
,new ShaderProperty("_Is_SpecularToHighColor", ShaderPropertyType.Float)
,new ShaderProperty("_Is_BlendAddToHiColor", ShaderPropertyType.Float)
,new ShaderProperty("_Is_UseTweakHighColorOnShadow", ShaderPropertyType.Float)
,new ShaderProperty("_TweakHighColorOnShadow", ShaderPropertyType.Range)
,new ShaderProperty("_Set_HighColorMask", ShaderPropertyType.TexEnv)
,new ShaderProperty("_Tweak_HighColorMaskLevel", ShaderPropertyType.Range)
,new ShaderProperty("_RimLight", ShaderPropertyType.Float)
,new ShaderProperty("_RimLightColor", ShaderPropertyType.Color)
,new ShaderProperty("_Is_LightColor_RimLight", ShaderPropertyType.Float)
,new ShaderProperty("_Is_NormalMapToRimLight", ShaderPropertyType.Float)
,new ShaderProperty("_RimLight_Power", ShaderPropertyType.Range)
,new ShaderProperty("_RimLight_InsideMask", ShaderPropertyType.Range)
,new ShaderProperty("_RimLight_FeatherOff", ShaderPropertyType.Float)
,new ShaderProperty("_LightDirection_MaskOn", ShaderPropertyType.Float)
,new ShaderProperty("_Tweak_LightDirection_MaskLevel", ShaderPropertyType.Range)
,new ShaderProperty("_Add_Antipodean_RimLight", ShaderPropertyType.Float)
,new ShaderProperty("_Ap_RimLightColor", ShaderPropertyType.Color)
,new ShaderProperty("_Is_LightColor_Ap_RimLight", ShaderPropertyType.Float)
,new ShaderProperty("_Ap_RimLight_Power", ShaderPropertyType.Range)
,new ShaderProperty("_Ap_RimLight_FeatherOff", ShaderPropertyType.Float)
,new ShaderProperty("_Set_RimLightMask", ShaderPropertyType.TexEnv)
,new ShaderProperty("_Tweak_RimLightMaskLevel", ShaderPropertyType.Range)
,new ShaderProperty("_MatCap", ShaderPropertyType.Float)
,new ShaderProperty("_MatCap_Sampler", ShaderPropertyType.TexEnv)
,new ShaderProperty("_BlurLevelMatcap", ShaderPropertyType.Range)
,new ShaderProperty("_MatCapColor", ShaderPropertyType.Color)
,new ShaderProperty("_Is_LightColor_MatCap", ShaderPropertyType.Float)
,new ShaderProperty("_Is_BlendAddToMatCap", ShaderPropertyType.Float)
,new ShaderProperty("_Tweak_MatCapUV", ShaderPropertyType.Range)
,new ShaderProperty("_Rotate_MatCapUV", ShaderPropertyType.Range)
,new ShaderProperty("_CameraRolling_Stabilizer", ShaderPropertyType.Float)
,new ShaderProperty("_Is_NormalMapForMatCap", ShaderPropertyType.Float)
,new ShaderProperty("_NormalMapForMatCap", ShaderPropertyType.TexEnv)
,new ShaderProperty("_BumpScaleMatcap", ShaderPropertyType.Range)
,new ShaderProperty("_Rotate_NormalMapForMatCapUV", ShaderPropertyType.Range)
,new ShaderProperty("_Is_UseTweakMatCapOnShadow", ShaderPropertyType.Float)
,new ShaderProperty("_TweakMatCapOnShadow", ShaderPropertyType.Range)
,new ShaderProperty("_Set_MatcapMask", ShaderPropertyType.TexEnv)
,new ShaderProperty("_Tweak_MatcapMaskLevel", ShaderPropertyType.Range)
,new ShaderProperty("_Inverse_MatcapMask", ShaderPropertyType.Float)
,new ShaderProperty("_Is_Ortho", ShaderPropertyType.Float)
,new ShaderProperty("_AngelRing", ShaderPropertyType.Float)
,new ShaderProperty("_AngelRing_Sampler", ShaderPropertyType.TexEnv)
,new ShaderProperty("_AngelRing_Color", ShaderPropertyType.Color)
,new ShaderProperty("_Is_LightColor_AR", ShaderPropertyType.Float)
,new ShaderProperty("_AR_OffsetU", ShaderPropertyType.Range)
,new ShaderProperty("_AR_OffsetV", ShaderPropertyType.Range)
,new ShaderProperty("_ARSampler_AlphaOn", ShaderPropertyType.Float)
,new ShaderProperty("_EMISSIVE", ShaderPropertyType.Float)
,new ShaderProperty("_Emissive_Tex", ShaderPropertyType.TexEnv)
,new ShaderProperty("_Emissive_Color", ShaderPropertyType.Color)
,new ShaderProperty("_Base_Speed", ShaderPropertyType.Float)
,new ShaderProperty("_Scroll_EmissiveU", ShaderPropertyType.Range)
,new ShaderProperty("_Scroll_EmissiveV", ShaderPropertyType.Range)
,new ShaderProperty("_Rotate_EmissiveUV", ShaderPropertyType.Float)
,new ShaderProperty("_Is_PingPong_Base", ShaderPropertyType.Float)
,new ShaderProperty("_Is_ColorShift", ShaderPropertyType.Float)
,new ShaderProperty("_ColorShift", ShaderPropertyType.Color)
,new ShaderProperty("_ColorShift_Speed", ShaderPropertyType.Float)
,new ShaderProperty("_Is_ViewShift", ShaderPropertyType.Float)
,new ShaderProperty("_ViewShift", ShaderPropertyType.Color)
,new ShaderProperty("_Is_ViewCoord_Scroll", ShaderPropertyType.Float)
,new ShaderProperty("_OUTLINE", ShaderPropertyType.Float)
,new ShaderProperty("_Outline_Width", ShaderPropertyType.Float)
,new ShaderProperty("_Farthest_Distance", ShaderPropertyType.Float)
,new ShaderProperty("_Nearest_Distance", ShaderPropertyType.Float)
,new ShaderProperty("_Outline_Sampler", ShaderPropertyType.TexEnv)
,new ShaderProperty("_Outline_Color", ShaderPropertyType.Color)
,new ShaderProperty("_Is_BlendBaseColor", ShaderPropertyType.Float)
,new ShaderProperty("_Is_LightColor_Outline", ShaderPropertyType.Float)
,new ShaderProperty("_Cutoff", ShaderPropertyType.Range)
,new ShaderProperty("_Is_OutlineTex", ShaderPropertyType.Float)
,new ShaderProperty("_OutlineTex", ShaderPropertyType.TexEnv)
,new ShaderProperty("_Offset_Z", ShaderPropertyType.Float)
,new ShaderProperty("_Is_BakedNormal", ShaderPropertyType.Float)
,new ShaderProperty("_BakedNormal", ShaderPropertyType.TexEnv)
,new ShaderProperty("_GI_Intensity", ShaderPropertyType.Range)
,new ShaderProperty("_Unlit_Intensity", ShaderPropertyType.Range)
,new ShaderProperty("_Is_Filter_LightColor", ShaderPropertyType.Float)
,new ShaderProperty("_Is_BLD", ShaderPropertyType.Float)
,new ShaderProperty("_Offset_X_Axis_BLD", ShaderPropertyType.Range)
,new ShaderProperty("_Offset_Y_Axis_BLD", ShaderPropertyType.Range)
,new ShaderProperty("_Inverse_Z_Axis_BLD", ShaderPropertyType.Float)

                        }
                    }
                );
            }
        }
    }
}
